// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyhfmkxqyoltjnjcfohu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5aGZta3hxeW9sdGpuamNmb2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNTc2NzIsImV4cCI6MjA4MjczMzY3Mn0.HvDi_nKBMFMqv7DJL5BSQRZ954DJrM-xNQeGVZ-xxTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});